### PR TITLE
Add support for RP2040

### PR DESCRIPTION
**Pull request by thewhobox**
This PR adds support for the RP2040.
Since the RP2040 has 4 timer you can set it with the define DALI_TIMER.
Default is 2.

### CODE REVIEW

**Comment by hubsif** [comment]
Hi Mike!
Thank you for the addition and the pull request! It pointed me to the [TimerInterrupt_Generic Library](https://github.com/khoih-prog/TimerInterrupt_Generic) which seems to be something I definitely need to look into. It seems it could make this library support much more hardware, e.g. there have been requests for ESP8266 support.

Your PR adds more changes, though, i.e. the removal of function default values. Since this might break existing implementations, may I ask what the reason for this is?

**Comment by thewhobox** [comment]
You're welcome.
I didn't know the library before, but we use it in another project.
Since TimerOne won't work on rp2040 i tried using the new lib.

I couldn't test it since my DALI PCB doesn't work and i am waiting for a new one.

The removal of the defaults are because otherwise it won't compile on rp2040. But the defaults are still working, because they are defined in the header.
https://forum.arduino.cc/t/default-arguments/40909/8

**Comment by thewhobox** [comment]
I got my new PCB and the lib is working just fine :)
Im not really satisfied with the actual result: had to hardcode a timer, so it is not possible to create a new DaliClass Instance and use this instead of the exported Dali variable (added define DALI_DONT_EXPORT)

But for now it works just great.
Thank you for this lib!

**Comment by thewhobox** [comment]
Closing this due it was in main branch...
Added more boards to be supported (ESP32, ESP8266*, AVR*).

*not tested

**Pull request closed without merging**
